// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kpyhigcqxrhliiyeteiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtweWhpZ2NxeHJobGlpeWV0ZWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTUwMzEyOTMsImV4cCI6MjA3MDYwNzI5M30.XVDaY8AU4QKHdZJshnRX_ZaSkMfc0NUhZUk0lnknvcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});